//! Spec §"Comments" — the file's leading comment block (exporter banner,
//! vertex/face counts) round-trips verbatim instead of being replaced by
//! the synthetic `# OBJ generated by oxideav-obj` header.

use oxideav_obj::obj;

/// A multi-line Blender-style header (the overwhelmingly common shape in
/// the wild) re-emits byte-for-byte at the top of the file.
#[test]
fn blender_style_header_round_trips_verbatim() {
    let src = "\
# Blender v2.93.0 OBJ File: 'scene.blend'
# www.blender.org
v 0.0 0.0 0.0
v 1.0 0.0 0.0
v 0.0 1.0 0.0
f 1 2 3
";
    let scene = obj::parse_obj(src).unwrap();
    let bytes = obj::serialize_obj(&scene, None).unwrap();
    let out = String::from_utf8(bytes).unwrap();

    // The synthetic banner is gone; the original two header lines lead.
    assert!(
        !out.contains("# OBJ generated by oxideav-obj"),
        "synthetic banner should be suppressed when a header block exists:\n{out}"
    );
    assert!(
        out.starts_with("# Blender v2.93.0 OBJ File: 'scene.blend'\n# www.blender.org\n"),
        "header block should lead the file verbatim:\n{out}"
    );
}

/// The spec's own §"Comments" example (`# 4 vertices` / `# 4 texture
/// vertices` / `# 4 normals`) survives, including the blank separator
/// line between two comment runs.
#[test]
fn spec_comment_example_with_internal_blank_survives() {
    let src = "\
# 4 vertices
# 4 texture vertices

# 4 normals
v 0 0 0
v 1 0 0
v 0 1 0
f 1 2 3
";
    let scene = obj::parse_obj(src).unwrap();
    let key = scene
        .extras
        .get("obj:header_comments")
        .expect("header comments captured");
    let arr = key.as_array().unwrap();
    let got: Vec<&str> = arr.iter().map(|v| v.as_str().unwrap()).collect();
    assert_eq!(
        got,
        vec!["# 4 vertices", "# 4 texture vertices", "", "# 4 normals"],
        "internal blank separator line is preserved inside the header block"
    );

    let bytes = obj::serialize_obj(&scene, None).unwrap();
    let out = String::from_utf8(bytes).unwrap();
    assert!(
        out.starts_with("# 4 vertices\n# 4 texture vertices\n\n# 4 normals\n"),
        "header block re-emits with its internal blank line:\n{out}"
    );
}

/// A file that opens directly with a directive (no leading comment) keeps
/// the synthetic banner and sets no `obj:header_comments` key.
#[test]
fn no_header_keeps_synthetic_banner() {
    let src = "v 0 0 0\nv 1 0 0\nv 0 1 0\nf 1 2 3\n";
    let scene = obj::parse_obj(src).unwrap();
    assert!(
        !scene.extras.contains_key("obj:header_comments"),
        "no header block ⇒ no extras key"
    );
    let bytes = obj::serialize_obj(&scene, None).unwrap();
    let out = String::from_utf8(bytes).unwrap();
    assert!(
        out.starts_with("# OBJ generated by oxideav-obj\n"),
        "synthetic banner is the fallback:\n{out}"
    );
}

/// Repeated decode → encode cycles are a fixed point — the header block
/// neither grows (trailing blank accumulation) nor shrinks.
#[test]
fn header_block_is_a_fixed_point() {
    let src = "\
# header line one
# header line two
v 0 0 0
v 1 0 0
v 0 1 0
f 1 2 3
";
    let scene1 = obj::parse_obj(src).unwrap();
    let bytes1 = obj::serialize_obj(&scene1, None).unwrap();
    let text1 = String::from_utf8(bytes1).unwrap();

    let scene2 = obj::parse_obj(&text1).unwrap();
    let bytes2 = obj::serialize_obj(&scene2, None).unwrap();
    let text2 = String::from_utf8(bytes2).unwrap();

    assert_eq!(text1, text2, "decode → encode is a stable fixed point");
    assert!(text1.starts_with("# header line one\n# header line two\n"));
}

/// A trailing blank line between the header and the first directive is
/// dropped on capture so it can't accumulate across round-trips; the
/// encoder owns the single separating newline.
#[test]
fn trailing_blank_after_header_is_dropped() {
    let src = "\
# only header

v 0 0 0
v 1 0 0
v 0 1 0
f 1 2 3
";
    let scene = obj::parse_obj(src).unwrap();
    let arr = scene
        .extras
        .get("obj:header_comments")
        .unwrap()
        .as_array()
        .unwrap();
    let got: Vec<&str> = arr.iter().map(|v| v.as_str().unwrap()).collect();
    assert_eq!(got, vec!["# only header"], "trailing blank stripped");
}
